inherit_from: .rubocop_todo.yml
require: 
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
AllCops:
  NewCops: enable
  Exclude:
    - 'config.ru'
    - 'Rakefile'
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/bundle/**/*'
Style/Documentation:
  Enabled: false
