name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Set up Ruby
      run: |
        sudo apt-get install -y libtag1-dev libmysqlclient-dev --no-install-recommends
        gem install bundler
        bundle install --jobs 4 --retry 3 --path vendor/bundle
    - name: Run RuboCop
      run: |
        bundle exec rubocop
